HISTORY_STEPS = 11
FUTURE_STEPS = 80
CURRENT_STEP_INDEX = 10
TOTAL_STEPS = HISTORY_STEPS + FUTURE_STEPS
TIMESTEP_SECONDS = 0.1
FUTURE_HORIZON_SECONDS = FUTURE_STEPS * TIMESTEP_SECONDS
MAXIMUM_ACCELERATION_METRES_PER_SECOND_SQUARED = 3.56
PREDICTED_OBJECT_TYPES = ("TYPE_VEHICLE", "TYPE_PEDESTRIAN", "TYPE_CYCLIST")
NUM_OBJECT_TYPES = len(PREDICTED_OBJECT_TYPES)
AGENT_TYPES = PREDICTED_OBJECT_TYPES + ("TYPE_OTHER",)
NUM_AGENT_TYPES = len(AGENT_TYPES)
STAGING_CROP_RADIUS_METRES = 400.0
MAP_POINT_SPACING_METRES = 1.0
MAP_CHUNK_DOTS = 20
NUM_PREDICTED_MODES = 6
STAGING_CODE_VERSION = "2026-08-19-a"

SUBMISSION_STEPS = 16
SUBMISSION_FIRST_SCENARIO_STEP = 15
SUBMISSION_STEP_STRIDE = FUTURE_STEPS // SUBMISSION_STEPS
SUBMISSION_FIRST_FUTURE_INDEX = SUBMISSION_FIRST_SCENARIO_STEP - (CURRENT_STEP_INDEX + 1)
SUBMISSION_FUTURE_INDICES = tuple(range(SUBMISSION_FIRST_FUTURE_INDEX, FUTURE_STEPS, SUBMISSION_STEP_STRIDE))
assert len(SUBMISSION_FUTURE_INDICES) == SUBMISSION_STEPS
assert SUBMISSION_FUTURE_INDICES[-1] == FUTURE_STEPS - 1

DISTANCE_NORMALISER_METRES = 65.8
LANE_CONTEXT_GRAPH_DISTANCE_NORMALISER_METRES = 321.3
VELOCITY_NORMALISER_METRES_PER_SECOND = 3.9
DIMENSION_NORMALISER_METRES = 1.6
SPEED_LIMIT_NORMALISER_MILES_PER_HOUR = 12.9

AGENT_POSITION = slice(0, 2)
AGENT_HEADING_COSINE = 2
AGENT_HEADING_SINE = 3
AGENT_VELOCITY = slice(4, 6)
AGENT_DIMENSIONS = slice(6, 8)
AGENT_TYPE = slice(8, 8 + NUM_AGENT_TYPES)
AGENT_IS_SDC = AGENT_TYPE.stop
AGENT_FEATURE_DIM = AGENT_IS_SDC + 1

PREDICTED_AGENT_ARRAY_SPEC = {
    "agent_history": (HISTORY_STEPS, AGENT_FEATURE_DIM),
    "agent_history_mask": (HISTORY_STEPS,),
    "future_positions": (FUTURE_STEPS, 2),
    "future_headings": (FUTURE_STEPS, 2),
    "future_mask": (FUTURE_STEPS,),
    "frame_origin": (2,),
    "frame_heading": (),
    "scenario_id": (),
    "track_id": (),
    "is_designated_target": (),
    "is_object_of_interest": (),
}

TRAFFIC_SIGNAL_STATES = (
    "LANE_STATE_UNKNOWN",
    "LANE_STATE_ARROW_STOP",
    "LANE_STATE_ARROW_CAUTION",
    "LANE_STATE_ARROW_GO",
    "LANE_STATE_STOP",
    "LANE_STATE_CAUTION",
    "LANE_STATE_GO",
    "LANE_STATE_FLASHING_STOP",
    "LANE_STATE_FLASHING_CAUTION",
)
NUM_TRAFFIC_SIGNAL_STATES = len(TRAFFIC_SIGNAL_STATES)

MAP_POLYLINE_KINDS = (
    "lane",
    "road_line",
    "road_edge",
    "stop_sign",
    "crosswalk",
    "speed_bump",
    "driveway",
)
NUM_MAP_POLYLINE_KINDS = len(MAP_POLYLINE_KINDS)

MAP_POSITION = slice(0, 2)
MAP_DIRECTION = slice(2, 4)
MAP_KIND = slice(4, 4 + NUM_MAP_POLYLINE_KINDS)
MAP_FEATURE_DIM = MAP_KIND.stop
POLYLINE_SIGNAL_DIM = HISTORY_STEPS * NUM_TRAFFIC_SIGNAL_STATES

LANE_TYPES = (
    "TYPE_UNDEFINED",
    "TYPE_FREEWAY",
    "TYPE_SURFACE_STREET",
    "TYPE_BIKE_LANE",
)
NUM_LANE_TYPES = len(LANE_TYPES)

MAP_LANE_TYPE = slice(MAP_KIND.stop, MAP_KIND.stop + NUM_LANE_TYPES)
MAP_SPEED_LIMIT = MAP_LANE_TYPE.stop
MAP_FEATURE_DIM = MAP_SPEED_LIMIT + 1

ROAD_LINE_TYPES = (
    "TYPE_UNKNOWN",
    "TYPE_BROKEN_SINGLE_WHITE",
    "TYPE_SOLID_SINGLE_WHITE",
    "TYPE_SOLID_DOUBLE_WHITE",
    "TYPE_BROKEN_SINGLE_YELLOW",
    "TYPE_BROKEN_DOUBLE_YELLOW",
    "TYPE_SOLID_SINGLE_YELLOW",
    "TYPE_SOLID_DOUBLE_YELLOW",
    "TYPE_PASSING_DOUBLE_YELLOW",
)

ROAD_EDGE_TYPES = (
    "TYPE_UNKNOWN",
    "TYPE_ROAD_EDGE_BOUNDARY",
    "TYPE_ROAD_EDGE_MEDIAN",
)
BOUNDARY_TYPES = ROAD_LINE_TYPES + ROAD_EDGE_TYPES
NUM_BOUNDARY_TYPES = len(BOUNDARY_TYPES)

MAP_BOUNDARY_TYPE = slice(MAP_SPEED_LIMIT + 1, MAP_SPEED_LIMIT + 1 + NUM_BOUNDARY_TYPES)
MAP_STOP_POINT = slice(MAP_BOUNDARY_TYPE.stop, MAP_BOUNDARY_TYPE.stop + 2)
MAP_LEFT_BOUNDARY_CROSSING = MAP_STOP_POINT.stop
MAP_RIGHT_BOUNDARY_CROSSING = MAP_LEFT_BOUNDARY_CROSSING + 1
MAP_FEATURE_DIM = MAP_RIGHT_BOUNDARY_CROSSING + 1
NUM_BOUNDARY_CROSSING_CODES = len(ROAD_LINE_TYPES) + 1

LANE_CONNECTION_KINDS = ("entry", "exit")
LANE_CONNECTION_SOURCE = 0
LANE_CONNECTION_DESTINATION = 1
LANE_CONNECTION_KIND = 2
LANE_CONNECTION_WIDTH = LANE_CONNECTION_KIND + 1

LANE_SIDES = ("left", "right")

LANE_NEIGHBOUR_LANE = 0
LANE_NEIGHBOUR_OTHER_LANE = 1
LANE_NEIGHBOUR_SIDE = 2
LANE_NEIGHBOUR_ID_WIDTH = LANE_NEIGHBOUR_SIDE + 1

LANE_NEIGHBOUR_SELF_START = slice(0, 2)
LANE_NEIGHBOUR_SELF_END = slice(2, 4)
LANE_NEIGHBOUR_OTHER_START = slice(4, 6)
LANE_NEIGHBOUR_OTHER_END = slice(6, 8)
LANE_NEIGHBOUR_BOUND_WIDTH = LANE_NEIGHBOUR_OTHER_END.stop

NO_SHARED_NEIGHBOUR_LANE = -1
LANE_BOUNDARY_LANE = 0
LANE_BOUNDARY_SHARED_NEIGHBOUR_LANE = 1
LANE_BOUNDARY_FEATURE = 2
LANE_BOUNDARY_SIDE = 3
LANE_BOUNDARY_TYPE = 4
LANE_BOUNDARY_ID_WIDTH = LANE_BOUNDARY_TYPE + 1

LANE_BOUNDARY_START = slice(0, 2)
LANE_BOUNDARY_END = slice(2, 4)
LANE_BOUNDARY_BOUND_WIDTH = LANE_BOUNDARY_END.stop

STOP_SIGN_FEATURE = 0
STOP_SIGN_CONTROLLED_LANE = 1
STOP_SIGN_LANE_WIDTH = STOP_SIGN_CONTROLLED_LANE + 1

LANE_CONTEXT_REACHABLE = 0
LANE_CONTEXT_GRAPH_DISTANCE = 1
LANE_CONTEXT_AGENT_LANE_DISTANCE = 2
LANE_CONTEXT_HAS_STOP_SIGN = 3
LANE_CONTEXT_REACHABLE_BY_LANE_CHANGE = 4
LANE_CONTEXT_CURVATURE = 5
LANE_CONTEXT_DIM = 6

def artifact_provenance(producer, source):
    import json
    return json.dumps({
        "code_version": STAGING_CODE_VERSION,
        "producer": producer,
        "source": str(source),
    })

def check_artifact_provenance(stored_provenance, artifact_path, regenerate_hint):
    import json
    assert stored_provenance is not None, (
        f"{artifact_path} carries no provenance stamp, so what produced it is unrecorded."
        f" {regenerate_hint}"
    )
    provenance = json.loads(str(stored_provenance))
    assert provenance["code_version"] == STAGING_CODE_VERSION, (
        f"{artifact_path} was produced under code_version {provenance['code_version']!r}"
        f" by {provenance['producer']} from {provenance['source']}, but the working tree is at"
        f" {STAGING_CODE_VERSION!r}. {regenerate_hint}"
    )
    return provenance
